export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const PUSH_ORDER = 'PUSH_ORDER';
export const PUSH_ORDER_SUCCESS = 'PUSH_ORDER_SUCCESS';
export const PUSH_ORDER_FAIL = 'PUSH_ORDER_FAIL';